version: "3"

services:
  test-db:
    image: postgres:15.1-alpine3.17
    container_name: test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: rpkm67_test_db
    volumes:
      - ./volumes/test:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  test-cache:
    image: redis:7.2.3-alpine
    container_name: test-cache
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: "5678"
    ports:
      - "6380:6379"