// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pin/pin.repository.go

// Package mock_pin is a generated GoMock package.
package mock_pin

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeletePin mocks base method.
func (m *MockRepository) DeletePin(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePin", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePin indicates an expected call of DeletePin.
func (mr *MockRepositoryMockRecorder) DeletePin(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePin", reflect.TypeOf((*MockRepository)(nil).DeletePin), key)
}

// GetPin mocks base method.
func (m *MockRepository) GetPin(key string, code interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPin", key, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPin indicates an expected call of GetPin.
func (mr *MockRepositoryMockRecorder) GetPin(key, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPin", reflect.TypeOf((*MockRepository)(nil).GetPin), key, code)
}

// SetPin mocks base method.
func (m *MockRepository) SetPin(key string, code interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPin", key, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPin indicates an expected call of SetPin.
func (mr *MockRepositoryMockRecorder) SetPin(key, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPin", reflect.TypeOf((*MockRepository)(nil).SetPin), key, code)
}
